version: '3.8'
name: Hilo_Multiplayer_BlazorWasm_v1
services:
  postgres-identity:
    image: postgres:16-alpine
    container_name: hilowasm-postgres-identity
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identityserver
    ports:
      - "25432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres-api:
    image: postgres:16-alpine
    container_name: hilowasm-postgres-api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hilo-gamedb
    ports:
      - "25433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-data:
